# Generated by Django 2.1.5 on 2019-01-12 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients_friend', to=settings.AUTH_USER_MODEL, verbose_name='друзья'),
        ),
    ]
