# Generated by Django 2.1.5 on 2019-01-12 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190112_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
